version: "3"
services:
    baba:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 50051-50053:50051
        volumes:
            - /:/home/ali
        image: baba-img
        networks: [default]
networks:
    default: 
        driver: bridge
        ipam:
            config:
              - subnet: 172.18.0.0/24